name: Mustackable Deploy

on:
  push:
    branches:
      - main 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.14

      - name: Install dependencies and build Next.js app
        run: |
          npm install
          npm run build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.PORT }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules
            **/.vscode
      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.8
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          include: '['.next','src','public','server,js','package.json']'
          passive: true
          
          
