name: Mustackable Deploy

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22.14

      - name: Install dependencies and build Next.js app
        run: |
          npm install
          npm run build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          port: ${{ secrets.DEPLOY_PORT }}
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.vscode*/**
            **/docs*/**
            .env*
            *.yaml
            *.mjs
            *.ts
            *.md
            tsconfig.json
            .prettierrc
            *.ts

      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_SSH_PORT }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASSPHRASE}}
          username: ${{secrets.DEPLOY_SSH_USERNAME}}
          key: ${{ secrets.DEPLOY_SSH_KEY}}
          script: |
            cd Mustackable
            ./deploy.sh
